# Generated by Django 5.2.16 on 2026-07-19 00:02

import uuid

from django.db import migrations, models

import apps.sharing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FitLogUser",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("user_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "split_type",
                    apps.sharing.models.PgEnumField(
                        blank=True, enum_name="WorkoutSplit", max_length=32, null=True
                    ),
                ),
                ("exercises", models.JSONField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "workout_templates",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        default=apps.sharing.models.generate_slug,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("owner_user_id", models.CharField(db_index=True, max_length=64)),
                (
                    "owner_first_name",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("WORKOUT_TEMPLATE", "Workout Template"),
                            ("NUTRITION_DAY", "Nutrition Day"),
                            ("WORKOUT_SESSION", "Workout Session"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("payload", models.JSONField()),
                ("view_count", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "share_links",
                "ordering": ["-created_at"],
            },
        ),
    ]
